---
  - hosts: test
    user: root
    become: yes 
    tasks:

    - name: Include variables
      include_vars:
        file: vault.yml

    - name: Update system
      ansible.builtin.include_role:
        name: updateall

    - name: install software
      ansible.builtin.include_role:
        name: install_software

    - name: create certificates
      ansible.builtin.include_role:
        name: create-certs

    - name: configuration open vpn
      ansible.builtin.include_role:
        name: config-openvpn

    - name: ufw install and configuration
      ansible.builtin.include_role:
        name: firewalld

    - name: configuration client
      ansible.builtin.include_role:
        name: config-client

    - name: check if openvpn is correct installed
      ansible.builtin.include_role:
        name: check


  
