---
- name: Install required software
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: present
  become: true
  loop:
    - epel-release
    - openvpn
    - easy-rsa

- name: Install pexpect
  ansible.builtin.dnf:
    name: python3-pexpect
    state: present
