---
- name: run dnf update
  ansible.builtin.dnf:
    name: "*"
    state: latest

- name: Install UFW
  ansible.builtin.dnf:
    name: ufw
    state: present

- name: Enabled UFW service
  ansible.builtin.service:
    name: ufw
    enabled: true

- name: Open poort 22 for SSH
  ansible.builtin.command:
    cmd: "/usr/sbin/ufw allow from any to any port '22' proto tcp comment 'Allow incoming SSH connections'"

- name: Open poort 443 for OpenVPN
  community.general.ufw:
    rule: allow
    port: '443'
    proto: tcp
    comment: Allow incoming OpenVPN connections

- name: Open poort 80 for Semaphore
  community.general.ufw:
    rule: allow
    port: '80'
    proto: tcp
    comment: Allow incoming HTTP connections for Semaphore

