---
# tasks file for firewalld
    - name: Install firewalld package
      yum:
        name: firewalld
        state: present

    - name: Enable and start firewalld
      service:
        name: firewalld
        state: started
        enabled: true

    - name: Allow SSH
      firewalld:
        service: ssh
        permanent: true
        state: enabled

    - name: Allow OpenVPN
      firewalld:
        port: 443/tcp
        permanent: true
        state: enabled

    - name: Reload firewalld
      command: firewall-cmd --reload