---
- name: Generate SSL certificates
  ansible.builtin.command: certbot certonly --agree-tos --email "{{ email }}" --standalone -d {{ item }}
  args:
    creates: "/etc/letsencrypt/live/{{ item }}"
  with_items: "{{ domains }}"
  become: true

- name: Renew certificates every 3 months
  ansible.builtin.cron:
    name: "Renew SSL certs (every 3 months)"
    job: "certbot renew --quiet --post-hook 'systemctl reload nginx'"
    # Schedule for renewal every 3 months at 4:30 AM
    minute: "30"
    hour: "4"
    month: "1,4,7,10"  # Months to run (January, April, July, October)
