services:
  mysql:
    restart: unless-stopped
    image: mysql:latest
    hostname: mysql
    volumes:
      - semaphore-mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${SQL_ROOT_PASSWD}
      MYSQL_DATABASE: semaphore
      MYSQL_USER: ${SEMA_DB_USER}
      MYSQL_PASSWORD: ${SQL_PASSWD}
    networks:
      - backend

  semaphore:
    restart: unless-stopped
    ports:
      - 80:3000
    build: .
    environment:
      SEMAPHORE_DB_USER: ${SEMA_DB_USER}
      SEMAPHORE_DB_PASS: ${SEMA_DB_PASSWORD}
      SEMAPHORE_DB_HOST: mysql 
      SEMAPHORE_DB_PORT: 3306 
      SEMAPHORE_DB_DIALECT: mysql
      SEMAPHORE_DB: semaphore
      SEMAPHORE_PLAYBOOK_PATH: /tmp/semaphore/
      SEMAPHORE_ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      SEMAPHORE_ADMIN_NAME: ${ADMIN_NAME}
      SEMAPHORE_ADMIN_EMAIL: admin@localhost
      SEMAPHORE_ADMIN: ${SEMA_ADMIN}
      SEMAPHORE_ACCESS_KEY_ENCRYPTION: ${ENCRYPTION_KEY}
      SEMAPHORE_LDAP_ACTIVATED: 'no' 
      SEMAPHORE_LDAP_HOST: dc01.local.example.com
      SEMAPHORE_LDAP_PORT: '636'
      SEMAPHORE_LDAP_NEEDTLS: 'yes'
      SEMAPHORE_LDAP_DN_BIND: 'uid=bind_user,cn=users,cn=accounts,dc=local,dc=shiftsystems,dc=net'
      SEMAPHORE_LDAP_PASSWORD: 'ldap_bind_account_password'
      SEMAPHORE_LDAP_DN_SEARCH: 'dc=local,dc=example,dc=com'
      SEMAPHORE_LDAP_SEARCH_FILTER: "(\u0026(uid=%s)(memberOf=cn=ipausers,cn=groups,cn=accounts,dc=local,dc=example,dc=com))"
      ANSIBLE_HOST_KEY_CHECKING: false
    depends_on:
      - mysql 
    networks:
      - backend
    volumes:
      - "/OVA/:/OVA/"

volumes:
  semaphore-mysql:
networks:
  backend:
    external: false